export { useSocket } from "./useSocket"
export { useLLM } from "./useLLM"
export { useSystemInfo, useTestWhisper, useGPUControl, useAudioDeviceConfig, useWhisperDeviceConfig, useWhisperConfig, getAudioConfig, setAudioConfig } from "./useSystemInfo"
export type { WhisperConfig } from "./useSystemInfo"
export { useAudioDiagnostics } from "./useAudioDiagnostics"
export { useMicrophone } from "./useMicrophone"
